"""Post-process AI-generated sprites:
1. Strip the checkered gray background → transparent
2. Crop the bottom watermark "Generated by MiniMax AI"
3. Save as PNG with alpha

Usage: python postprocess.py
Reads from ./ (sprite_tests/) and writes to ../stellar_horizon/assets/sprites_v2/
"""
from __future__ import annotations

import os
from pathlib import Path
from PIL import Image


HERE = Path(__file__).resolve().parent
SRC = HERE
DST = HERE.parent / "stellar_horizon" / "assets" / "sprites_v2"
DST.mkdir(parents=True, exist_ok=True)


def is_checkered_gray(px: tuple[int, int, int, int], tol: int = 8) -> bool:
    """True if pixel looks like part of the AI checkered background.
    The checkered pattern is gray (R==G==B) in the medium range (80-220).
    Saturated colors and very dark/very light pixels are NOT background.
    """
    if len(px) < 3:
        return False
    r, g, b = px[0], px[1], px[2]
    if abs(r - g) > tol or abs(g - b) > tol or abs(r - b) > tol:
        return False  # not gray
    if r < 60 or r > 230:
        return False  # too dark or too light to be background
    return True


def process_one(src: Path, dst: Path) -> tuple[int, int, int]:
    """Returns (orig_size, transparent_pixels, cropped_height)."""
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    px = img.load()

    transparent_count = 0
    for y in range(h):
        for x in range(w):
            if is_checkered_gray(px[x, y]):
                px[x, y] = (0, 0, 0, 0)
                transparent_count += 1

    # Crop bottom 6% (the "Generated by MiniMax AI" watermark strip)
    crop_h = int(h * 0.06)
    cropped = img.crop((0, 0, w, h - crop_h))

    # Save as PNG
    dst.parent.mkdir(parents=True, exist_ok=True)
    cropped.save(dst, "PNG", optimize=True)
    return w, h, transparent_count, (h - crop_h)


def main() -> None:
    files = sorted(SRC.glob("*.jpg"))
    if not files:
        print("No .jpg files found in", SRC)
        return
    print(f"Processing {len(files)} files -> {DST}")
    total_orig = 0
    total_cropped = 0
    for f in files:
        out = DST / (f.stem + ".png")
        try:
            w, h_orig, tcount, h_new = process_one(f, out)
            total_orig += h_orig
            total_cropped += h_new
            print(f"  {f.name} -> {out.name}  {w}x{h_orig} -> {w}x{h_new}  ({tcount} px transparent)")
        except Exception as e:
            print(f"  {f.name}  FAILED: {e}")
    print(f"Done. Orig total H: {total_orig}  Cropped total H: {total_cropped}")


if __name__ == "__main__":
    main()
