"""Crop+rescale a single AI-generated laser strip into a 900x50 input for postprocess.

2026-09-08 v1.5: long-format variant of regen_laser_strip_one.py. The
target size is 150x50 per frame (vs 29x7 in the compact format), giving
6 frames in a row = 900x50. The output is the "charged state" sprite
for the 4 new weapons (cyan ice, orange flame, white lightning, magenta
heart), used as a charge-preview on the ship.

Pipeline (mirrors regen_laser_strip_one.py):
1. Load raw image from Matrix.
2. Find the colored content bbox (excluding AI watermark + white margin).
3. Split the content into 6 vertical slices (one per frame).
4. Rotate each slice 90 degrees CCW (vertical beam -> horizontal).
5. Resize each to 150 wide, keep aspect, fit to 50 rows tall.
6. Concatenate the 6 frames horizontally -> 900x50.
7. Quantize near-white background pixels to pure white so the
   postprocess floodfill catches them.

Usage:
    python -m sprite_tests.regen_laser_strip_one_long <raw.png> <out_strip.png>
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image


# 2026-09-08 v1.5: long format — each frame is 150x50 (5x wider,
# 7x taller than the compact 29x7). 6 frames per weapon.
W_TARGET = 900
FRAME_W = 150
N_FRAMES = 6
FRAME_H = 50


def find_color_bbox(img: Image.Image) -> tuple[int, int, int, int]:
    """Bounding box of pixels that are neither near-white nor near-black.

    Excludes the white background and the black AI watermark ("Generated by...").
    """
    w, h = img.size
    px = img.load()
    xs: list[int] = []
    ys: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if r > 240 and g > 240 and b > 240:
                continue
            if r < 30 and g < 30 and b < 30:
                continue
            xs.append(x)
            ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


def split_rotate_resize(content: Image.Image) -> Image.Image:
    """Split the colored content into 6 vertical slices, rotate, resize, fit.

    Returns a 900x50 RGB strip with a clean white background.
    """
    cw, ch = content.size
    slice_w = cw // N_FRAMES
    frames: list[Image.Image] = []
    for i in range(N_FRAMES):
        slc = content.crop((i * slice_w, 0, (i + 1) * slice_w, ch))
        # 90 CCW: top of vertical beam becomes left side of horizontal beam
        slc = slc.rotate(90, expand=True)
        # Resize to FRAME_W wide, keep aspect
        new_w = FRAME_W
        new_h = max(1, int(slc.size[1] * new_w / slc.size[0]))
        slc = slc.resize((new_w, new_h), Image.LANCZOS)
        # Fit to FRAME_W x FRAME_H (pad or center-crop)
        if slc.size[1] < FRAME_H:
            new_slc = Image.new("RGB", (FRAME_W, FRAME_H), (255, 255, 255))
            new_slc.paste(slc, (0, (FRAME_H - slc.size[1]) // 2))
            slc = new_slc
        elif slc.size[1] > FRAME_H:
            y0 = (slc.size[1] - FRAME_H) // 2
            slc = slc.crop((0, y0, FRAME_W, y0 + FRAME_H))
        frames.append(slc)
    # Concatenate horizontally
    strip = Image.new("RGB", (W_TARGET, FRAME_H), (255, 255, 255))
    for i, f in enumerate(frames):
        strip.paste(f, (i * FRAME_W, 0))
    return strip


def quantize_background(strip: Image.Image) -> Image.Image:
    """Round all near-white pixels to pure (255, 255, 255)."""
    px = strip.load()
    for y in range(strip.size[1]):
        for x in range(strip.size[0]):
            r, g, b = px[x, y]
            if r > 240 and g > 240 and b > 240:
                px[x, y] = (255, 255, 255)
    return strip


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"Usage: {argv[0]} <raw.png> <out_strip.png>", file=sys.stderr)
        return 1
    raw = Image.open(argv[1]).convert("RGB")
    x0, y0, x1, y1 = find_color_bbox(raw)
    content = raw.crop((x0, y0, x1 + 1, y1 + 1))
    strip = split_rotate_resize(content)
    strip = quantize_background(strip)
    strip.save(argv[2], format="PNG")
    print(f"Strip saved: {strip.size} -> {argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
