"""Right-align postprocess for the 150x50 long-format laser sheets.

2026-09-08 v1.5: long-format variant of regen_laser_strip_six.py.
Same pipeline (clean gray pixels, floodfill, right-align paste) but
target size is 150x50 per frame (vs 29x7 in the compact format),
giving 6 frames in a row = 900x50.

Used to postprocess the 4 long sheets (laser_06 cyan, laser_07
orange, laser_08 white, laser_09 magenta) into the "charged state"
sprites for the new weapons.

Usage:
    python -m sprite_tests.regen_laser_strip_six_long <input_strip.png> <output_dir> [name]
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import List, Tuple

from PIL import Image, ImageDraw


# 2026-09-08 v1.5: long format. 6 frames at 150x50 each = 900x50.
FRAME_W = 150
FRAME_H = 50
N_FRAMES = 6
STRIP_W = FRAME_W * N_FRAMES  # 900


def clean_gray_pixels(img: Image.Image) -> Image.Image:
    """Clear near-gray pixels (AI watermark anti-aliasing) to transparent.

    Same logic as the compact postprocess: keep saturated pixels
    (the actual sprite content) and very dark pixels (outlines).
    Strip light-gray pixels (the "Generated by..." watermark and
    its anti-aliased edges).
    """
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    work = img.copy()
    px = work.load()
    for y in range(work.size[1]):
        for x in range(work.size[0]):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            # Pure black: keep (used for outlines).
            if r < 30 and g < 30 and b < 30:
                continue
            # Near-equal channels (gray / watermark).
            if max(r, g, b) - min(r, g, b) < 30:
                px[x, y] = (0, 0, 0, 0)
                continue
            # Light-but-desaturated: strip more watermark edges.
            if r > 225 and g > 245 and b > 245 and (b - r) < 50:
                px[x, y] = (0, 0, 0, 0)
    return work


def split_strip_to_frames(strip: Image.Image) -> List[Image.Image]:
    if strip.size[0] != STRIP_W:
        raise ValueError(f"Expected strip width {STRIP_W}, got {strip.size[0]}")
    if strip.size[1] < FRAME_H:
        raise ValueError(f"Expected strip height >= {FRAME_H}, got {strip.size[1]}")
    return [
        strip.crop((i * FRAME_W, 0, (i + 1) * FRAME_W, FRAME_H))
        for i in range(N_FRAMES)
    ]


def crop_to_content(frame: Image.Image) -> Image.Image:
    """Floodfill from corner to clear background, then crop to bbox."""
    if frame.mode != "RGBA":
        frame = frame.convert("RGBA")
    work = frame.copy()
    r, g, b, a = work.getpixel((0, 0))
    if r > 200 and g > 200 and b > 200:
        ImageDraw.floodfill(work, (0, 0), value=(0, 0, 0, 0))
    elif r < 50 and g < 50 and b < 50:
        ImageDraw.floodfill(work, (0, 0), value=(0, 0, 0, 0))
    # Aggressive cleanup: clear any remaining near-white pixels.
    px = work.load()
    for y in range(work.size[1]):
        for x in range(work.size[0]):
            pr, pg, pb, pa = px[x, y]
            if pr > 235 and pg > 235 and pb > 235:
                px[x, y] = (0, 0, 0, 0)
    bbox = work.getbbox()
    if bbox is None:
        return Image.new("RGBA", (1, 1), (0, 0, 0, 0))
    left, top, right, bottom = bbox
    left = max(0, left - 1)
    top = max(0, top)
    right = min(frame.size[0], right + 1)
    bottom = min(frame.size[1], bottom + 1)
    return work.crop((left, top, right, bottom))


def _right_align_paste(canvas: Image.Image, content: Image.Image) -> None:
    """Paste content right-aligned on canvas (in place)."""
    cw, ch = canvas.size
    iw, ih = content.size
    x = cw - iw  # right-align
    y = (ch - ih) // 2  # vertical center
    if y < 0:
        y = 0
    canvas.alpha_composite(content, (x, y))


def assemble_sheet(frames: List[Image.Image]) -> Image.Image:
    if len(frames) != N_FRAMES:
        raise ValueError(f"Expected {N_FRAMES} frames, got {len(frames)}")
    sheet = Image.new("RGBA", (STRIP_W, FRAME_H), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (i * FRAME_W, 0))
    return sheet


def process_strip(in_path: Path, out_dir: Path, name: str) -> Tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    strip = Image.open(str(in_path))
    if strip.mode != "RGBA":
        strip = strip.convert("RGBA")
    # Remove AI-watermark gray artifacts before splitting into frames.
    strip = clean_gray_pixels(strip)
    raw_frames = split_strip_to_frames(strip)
    processed: List[Image.Image] = []
    for f in raw_frames:
        cropped = crop_to_content(f)
        canvas = Image.new("RGBA", (FRAME_W, FRAME_H), (0, 0, 0, 0))
        _right_align_paste(canvas, cropped)
        processed.append(canvas)
    sheet = assemble_sheet(processed)
    sheet_path = out_dir / f"{name}_sheet.png"
    sheet.save(str(sheet_path), format="PNG")
    ref_path = out_dir / f"{name}.png"
    processed[0].save(str(ref_path), format="PNG")
    return sheet_path, ref_path


def main(argv: list[str]) -> int:
    if len(argv) not in (3, 4):
        print(f"Usage: {argv[0]} <input_strip.png> <output_dir> [name]", file=sys.stderr)
        return 1
    in_path = Path(argv[1])
    out_dir = Path(argv[2])
    if len(argv) == 4:
        name = argv[3]
    else:
        stem = in_path.stem
        name = stem[:-6] if stem.endswith("_strip") else stem
    sheet, ref = process_strip(in_path, out_dir, name)
    print(f"Sheet: {sheet}")
    print(f"Reference: {ref}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
