"""Crop+rescale a single AI-generated laser strip into a 174x7 input for postprocess.

This handles the AI's two layout variants (horizontal beam vs vertical beam)
and the watermark/anti-aliasing quirks observed for visual-polish-v3 Task 7.

Pipeline:
1. Load raw 1200x896 image from Matrix.
2. Find the colored content bbox (excluding the AI watermark + white margin).
3. Split the content into 6 vertical slices (one per frame).
4. Rotate each slice 90 degrees CCW (vertical beam -> horizontal).
5. Resize each to 29 wide, keep aspect, fit to 7 rows tall.
6. Concatenate the 6 frames horizontally -> 174x7.
7. Quantize near-white background pixels to pure white so the postprocess
   floodfill catches them.

Usage:
    python -m sprite_tests.regen_laser_strip_one <raw.png> <out_strip.png>
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image


W_TARGET = 174
FRAME_W = 29
N_FRAMES = 6
FRAME_H = 7


def find_color_bbox(img: Image.Image) -> tuple[int, int, int, int]:
    """Bounding box of pixels that are neither near-white nor near-black.

    Excludes the white background and the black AI watermark ("Generated by...").
    """
    w, h = img.size
    px = img.load()
    xs: list[int] = []
    ys: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            if r > 240 and g > 240 and b > 240:
                continue
            if r < 30 and g < 30 and b < 30:
                continue
            xs.append(x)
            ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


def split_rotate_resize(content: Image.Image) -> Image.Image:
    """Split the colored content into 6 vertical slices, rotate, resize, fit.

    Returns a 174x7 RGB strip with a clean white background.
    """
    cw, ch = content.size
    slice_w = cw // N_FRAMES
    frames: list[Image.Image] = []
    for i in range(N_FRAMES):
        slc = content.crop((i * slice_w, 0, (i + 1) * slice_w, ch))
        # 90 CCW: top of vertical beam becomes left side of horizontal beam
        slc = slc.rotate(90, expand=True)
        # Resize to 29 wide, keep aspect
        new_w = FRAME_W
        new_h = max(1, int(slc.size[1] * new_w / slc.size[0]))
        slc = slc.resize((new_w, new_h), Image.LANCZOS)
        # Fit to 29x7 (pad or center-crop)
        if slc.size[1] < FRAME_H:
            new_slc = Image.new("RGB", (FRAME_W, FRAME_H), (255, 255, 255))
            new_slc.paste(slc, (0, (FRAME_H - slc.size[1]) // 2))
            slc = new_slc
        elif slc.size[1] > FRAME_H:
            y0 = (slc.size[1] - FRAME_H) // 2
            slc = slc.crop((0, y0, FRAME_W, y0 + FRAME_H))
        frames.append(slc)
    # Concatenate horizontally
    strip = Image.new("RGB", (W_TARGET, FRAME_H), (255, 255, 255))
    for i, f in enumerate(frames):
        strip.paste(f, (i * FRAME_W, 0))
    return strip


def quantize_background(strip: Image.Image) -> Image.Image:
    """Round all near-white pixels to pure (255, 255, 255).

    The postprocess floodfills by exact color match. AI anti-aliasing produces
    pixels like (255, 253, 253) which would not be cleared. Quantizing them
    to pure white ensures the floodfill reaches the laser's soft edge.
    """
    px = strip.load()
    for y in range(strip.size[1]):
        for x in range(strip.size[0]):
            r, g, b = px[x, y]
            if r > 240 and g > 240 and b > 240:
                px[x, y] = (255, 255, 255)
    return strip


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"Usage: {argv[0]} <raw.png> <out_strip.png>", file=sys.stderr)
        return 1
    raw = Image.open(argv[1]).convert("RGB")
    x0, y0, x1, y1 = find_color_bbox(raw)
    content = raw.crop((x0, y0, x1 + 1, y1 + 1))
    strip = split_rotate_resize(content)
    strip = quantize_background(strip)
    strip.save(argv[2], format="PNG")
    print(f"Strip saved: {strip.size} -> {argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
